# Generated by Django 4.1 on 2022-11-30 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("borrowings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowing",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrowings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("borrow_date__lte", django.db.models.functions.datetime.Now())
                ),
                name="check_borrowing_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "expected_return_date__gt",
                        django.db.models.functions.datetime.Now(),
                    )
                ),
                name="check_expected_return_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                check=models.Q(("expected_return_date__gte", models.F("borrow_date"))),
                name="check_expected_return_is_after_borrow",
            ),
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "actual_return_date__gte",
                        django.db.models.functions.datetime.Now(),
                    )
                ),
                name="check_return_date",
            ),
        ),
    ]
